In [73]:
import pandas as pd

In [74]:
# df1 = pd.read_csv('Apple_test_cleaned.csv', encoding='latin-1')

In [75]:
# df1.info()

In [76]:
# df1 = df1.drop(['_golden','_unit_state','_trusted_judgments','_last_judgment_at','date','id','query','sentiment_gold'], axis=1)

In [77]:
# df1 = df1.to_csv("Apple_test_cleaned.csv", index=False)

In [78]:
# df1.isnull().sum()

##### The 82 rows with not_relevant sentiment have been removed. The DataFrame now only contains the relevant sentiment values:

In [79]:
# df1 = df1[df1['sentiment'] != 'not_relevant']
# df1['sentiment'].value_counts()

##### 79 rows with fewer than 5 words in the text column were removed (3804 → 3725 rows remaining).

In [80]:
# print("Before:", len(df1))
# df1 = df1[df1['text'].str.split().str.len() >= 5]
# print("After:", len(df1))

In [81]:
# df1.to_csv("Apple_test_cleaned2.csv", index=False)

In [ ]:
# df2 = pd.read_csv("D:\\ML CODES\\IBM\\TEST_CLEANED\\IMDB Dataset.csv")

In [ ]:
# df2.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
# df2 = df2[['reviews.text']]

In [ ]:
# df2.to_csv('hotel_test_cleaned.csv',index=False)

In [ ]:
# df3 = pd.read_csv("D:\\ML CODES\\IBM\\test\\socialmedia-test.csv",encoding='latin-1')

In [ ]:
# df3.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,keyword,location,text,tweetid,userid
0,778243823,True,golden,156,NaN,Relevant,1.0000,Relevant,NaN,NaN,Just happened a terrible car crash,1.0,NaN
1,778243824,True,golden,152,NaN,Relevant,1.0000,Relevant,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,13.0,NaN
2,778243825,True,golden,137,NaN,Relevant,1.0000,Relevant,NaN,NaN,"Heard about #earthquake is different cities, s...",14.0,NaN
3,778243826,True,golden,136,NaN,Relevant,0.9603,Relevant,NaN,NaN,"there is a forest fire at spot pond, geese are...",15.0,NaN
4,778243827,True,golden,138,NaN,Relevant,1.0000,Relevant,NaN,NaN,Forest fire near La Ronge Sask. Canada,16.0,NaN

In [ ]:
# df3 = df3[['text']]

In [133]:
df2.head(60)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production br br The filmin...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically theres a family where a little boy J...  negative
4   Petter Matteis Love in the Time of Money is a ...  positive
5   Probably my alltime favorite movie a story of ...  positive
6   I sure would like to see a resurrection of a u...  positive
7   This show was an amazing fresh  innovative ide...  negative
8   Encouraged by the positive comments about this...  negative
9   If you like original gut wrenching laughter yo...  positive
10  Phil the Alien is one of those quirky films wh...  negative
11  I saw this movie when I was about 12 when it c...  negative
12  So im not a big fan of Bolls work but then aga...  negative
13  The cast played Shakespearebr br Shakespeare l...  negative
14  This a fantastic movie of three prisoners who ...  positive
15  Kind of drawn in by the erotic scenes only to ...  negative
16  Some films just simply should not be remade Th...  positive
17  This movie made it into one of my top 10 most ...  negative
18  I remember this filmit was the first film i ha...  positive
19  An awful film It must have been up against som...  negative
20  After the success of Die Hard and its sequels ...  positive
21  I had the terrible misfortune of having to vie...  negative
22  What an absolutely stunning movie if you have ...  positive
23  First of all lets get a few things straight he...  negative
24  This was the worst movie I saw at WorldFest an...  negative
25  The Karen Carpenter Story shows a little more ...  positive
26  The Cell is an exotic masterpiece a dizzying t...  positive
27  This film tried to be too many things all at o...  negative
28  This movie was so frustrating Everything seeme...  negative
29  War movie is a Hollywood genre that has been d...  positive
30  Taut and organically gripping Edward Dmytryks ...  positive
31  Ardh Satya is one of the finest film ever made...  positive
32  My first exposure to the Templarios  not a goo...  negative
33  One of the most significant quotes from the en...  positive
34  I watched this film not really expecting much ...  negative
35  I bought this film at Blockbuster for 300 beca...  negative
36  The plot is about the death of little children...  negative
37  Ever watched a movie that lost the plot Well t...  negative
38  Okay so this series kind of takes the route of...  positive
39  After sitting through this pile of dung my hus...  negative
40  It had all the clichés of movies of this type ...  negative
41  This movie is based on the book A Many Splendo...  positive
42  Of all the films I have seen this one The Rage...  negative
43  I had heard good things about States of Grace ...  negative
44  This movie struck home for me Being 29 I remem...  positive
45  As a disclaimer Ive seen the movie 56 times in...  positive
46  Protocol is an implausible movie whose only sa...  negative
47  How this film could be classified as Drama I h...  negative
48  Preston Sturgis THE POWER AND THE GLORY was un...  positive
49  Average and surprisingly tame Fulci giallo whi...  negative
50  Return to the 36th Chamber is one of those cla...  positive
51  SPOILERS All too in real life as well as in th...  positive
52  Bela Lugosi appeared in several of these low b...  positive
53  I cannot believe I enjoyed this as much as I d...  positive
54  The 33 percent of the nations nitwits that sti...  negative
55  As someone has already mentioned on this board...  negative
56  The Hills Have Eyes II is what you would expec...  negative
57  I laughed all the way through this rotten movi...  negative
58  NO SPOILERSbr br After Hitchcocks successful f...  positive
59  I just watched The Dresser this evening having...  positive

In [126]:
print("df2 duplicates:", df2.duplicated().sum())

df2 duplicates: 0

In [125]:
df2.drop_duplicates(inplace=True)

##### Remove URLs

In [129]:
df2['review'] = df2['review'].str.replace(r"http\S+|www\S+", "", regex=True)

##### Remoev @ mentions

In [130]:
import re

df2["review"] = df2["review"].apply(lambda x: re.sub(r"@\w+", "", x))

##### Remove Punctuations

In [131]:
df2["review"] = df2["review"].apply(lambda x: re.sub(r"[^\w\s]", "", x))

#### handle elongated words

In [132]:


def remove_elongated_words(text):
    return re.sub(r'(.)\1{2,}', r'\1\1', text)

df2["review"] = df2["review"].apply(remove_elongated_words)

In [134]:
df2.to_csv("IMDB_Dataset_cleaned.csv", index=False)