In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('movies.csv')
df = df.head(5000)  # Limit to first 5000 rows
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [39]:
df = df[['title', 'genres', 'movieId']]
df =df.fillna('')
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    5000 non-null   object
 1   genres   5000 non-null   object
 2   movieId  5000 non-null   int64
dtypes: int64(1), object(2)
memory usage: 117.3+ KB

In [40]:
# Remove year from title (e.g., "Toy Story (1995)" -> "Toy Story")
df['title'] = df['title'].str.replace(r'\s*\(\d{4}\)', '', regex=True)
df.head()

,title,genres,movieId
0,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1
1,Jumanji,Adventure|Children|Fantasy,2
2,Grumpier Old Men,Comedy|Romance,3
3,Waiting to Exhale,Comedy|Drama|Romance,4
4,Father of the Bride Part II,Comedy,5

In [41]:
df['features'] = df['title'] + ' ' + df['genres'] + ' ' + df['movieId'].astype(str)

In [42]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english',min_df=20)
word_matrix = cv.fit_transform(df['features'])
word_matrix.shape

(5000, 53)

In [43]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(word_matrix)

In [44]:
def recommend(title,df,sim,count=10):
    index = df.index[df['title'].str.lower() == title.lower()]

    if len(index) == 0:
        return "Movie not found in the database."
    
    similar_movies = list(enumerate(sim[index[0]]))
    recommendation = sorted(similar_movies, key=lambda x: x[1], reverse=True)

    top_recs = recommendation[1:count+1]
    titles = []
    for i in range(len(top_recs)):
        title = df.iloc[top_recs[i][0]]['title']
        titles.append(title)
    return titles

In [45]:
recommend('Toy Story (1995)',df,sim)

'Movie not found in the database.'